### ISSUE TITLE
W&B 失效了

### ISSUE THREAD

**Issue by pengwork** [zhanshijinwat/Steel-LLM#4]
https://wandb.ai/steel-llm-lab/lightning_logs/reports/Untitled-Report--Vmlldzo4NzI1MTQz

<img width="815" alt="image" src="https://github.com/user-attachments/assets/8bb54b29-03fd-4548-9c6e-c0a186da52ac">

**Comment by zhanshijinwat** [comment]
https://wandb.ai/steel-llm-lab/lightning_logs/reports/Untitled-Report--Vmlldzo5OTg1Mjgw?accessToken=4eilxq5fzt75a9br88ffolucjllmqnt2wwk9czp7pywx54ppnec4ftqnk9k05kkt
