### ISSUE TITLE
请教关于针对不同的数据来源的采样问题，请问是否支持，后续是否打算支持？

### ISSUE THREAD

**Issue by jerry1993-tech** [zhanshijinwat/Steel-LLM#6]
【按照数据来源的上、下采样
不同的数据来源实际代表着不同的数据质量、不同的专业性、不同的领域，要结合预训练模型的目标，对不同的数据来源采用不同的采样率，有些数据来源需要上采样，有些数据来源可能需要下采样。不同大模型重新混合的采样策略也是不尽相同的，大体上的思路是：对高质量数据比如维基百科进行上采样，对低质量数据比如一般Web网页可能进行下采样。下面给几个例子：

GPT3 对于维基百科等效进行了3.4倍的上采样，对于经过精心处理的WebText2（尽管是网页数据）也等效进行了2.9倍的上采样，对于 CommonCrawl（即使过滤过）等效进行了44%的下采样；
Llama 也是对于维基百科和数据进行了上采样，没有对一般网页进行下采样，对于代码数据反倒是进行了下采样，毕竟不是专门的Code大模型；
Baichuan 2、DeepSeek 都提到了按照领域（domain）的原始数据占比进行的remix采样，应该主要是通过上采样来平衡较少出现领域的训练Token占比，提升训练数据的 diversity；
![remix](https://github.com/user-attachments/assets/91ecd5c9-60d4-4edc-912a-501049b6abd1)
】

博主您好，请问两个问题：
1. 针对不同的数据来源采用不同的采样率框架是否支持，后续是否有相关打算？
2. 针对不同大类的数据的loss观测，channel_loss 是否支持，后续是否有相关打算？
谢谢！！！

**Comment by zhanshijinwat** [comment]
1.这个很好加，就保存时候sample一个数，小于或者或者大于某个值才把数据存下来，有时间我搞下吧
2.这个比较费劲，我用的这些开源数据都没有文本类别
